In [1]:
import plotly.graph_objects as go # or plotly.express as px
from plotly.subplots import make_subplots
import json
import pandas as pd
import numpy as np

In [2]:
with open ("pokedex.json") as p: 
    pokedex=json.load(p)

In [3]:
type(pokedex)

dict

In [4]:
pokedex.keys

In [5]:
type (pokedex["pokemon"])

list

In [6]:
len(pokedex["pokemon"])

151

In [7]:
pokedex["pokemon"][0]

{'id': 1,
 'num': '001',
 'name': 'Bulbasaur',
 'img': 'http://www.serebii.net/pokemongo/pokemon/001.png',
 'type': ['Grass', 'Poison'],
 'height': '0.71 m',
 'weight': '6.9 kg',
 'candy': 'Bulbasaur Candy',
 'candy_count': 25,
 'egg': '2 km',
 'spawn_chance': 0.69,
 'avg_spawns': 69,
 'spawn_time': '20:00',
 'multipliers': [1.58],
 'weaknesses': ['Fire', 'Ice', 'Flying', 'Psychic'],
 'next_evolution': [{'num': '002', 'name': 'Ivysaur'},
  {'num': '003', 'name': 'Venusaur'}]}

In [8]:
pokedex["pokemon"][0].keys()

dict_keys(['id', 'num', 'name', 'img', 'type', 'height', 'weight', 'candy', 'candy_count', 'egg', 'spawn_chance', 'avg_spawns', 'spawn_time', 'multipliers', 'weaknesses', 'next_evolution'])

In [9]:
pokedata = pd.DataFrame(pokedex["pokemon"])

pokedata.head()

,id,num,name,img,type,height,weight,candy,candy_count,egg,spawn_chance,avg_spawns,spawn_time,multipliers,weaknesses,next_evolution,prev_evolution
0,1,001,Bulbasaur,http://www.serebii.net/pokemongo/pokemon/001.png,"[Grass, Poison]",0.71 m,6.9 kg,Bulbasaur Candy,25.0,2 km,0.690,69.0,20:00,[1.58],"[Fire, Ice, Flying, Psychic]","[{'num': '002', 'name': 'Ivysaur'}, {'num': '0...",NaN
1,2,002,Ivysaur,http://www.serebii.net/pokemongo/pokemon/002.png,"[Grass, Poison]",0.99 m,13.0 kg,Bulbasaur Candy,100.0,Not in Eggs,0.042,4.2,07:00,"[1.2, 1.6]","[Fire, Ice, Flying, Psychic]","[{'num': '003', 'name': 'Venusaur'}]","[{'num': '001', 'name': 'Bulbasaur'}]"
2,3,003,Venusaur,http://www.serebii.net/pokemongo/pokemon/003.png,"[Grass, Poison]",2.01 m,100.0 kg,Bulbasaur Candy,NaN,Not in Eggs,0.017,1.7,11:30,None,"[Fire, Ice, Flying, Psychic]",NaN,"[{'num': '001', 'name': 'Bulbasaur'}, {'num': ..."
3,4,004,Charmander,http://www.serebii.net/pokemongo/pokemon/004.png,[Fire],0.61 m,8.5 kg,Charmander Candy,25.0,2 km,0.253,25.3,08:45,[1.65],"[Water, Ground, Rock]","[{'num': '005', 'name': 'Charmeleon'}, {'num':...",NaN
4,5,005,Charmeleon,http://www.serebii.net/pokemongo/pokemon/005.png,[Fire],1.09 m,19.0 kg,Charmander Candy,100.0,Not in Eggs,0.012,1.2,19:00,[1.79],"[Water, Ground, Rock]","[{'num': '006', 'name': 'Charizard'}]","[{'num': '004', 'name': 'Charmander'}]"

In [10]:
pokedata[["type1", "type2"]] = pd.DataFrame(pokedata.type.to_list(), index = pokedata.index)

pokedata.head()

,id,num,name,img,type,height,weight,candy,candy_count,egg,spawn_chance,avg_spawns,spawn_time,multipliers,weaknesses,next_evolution,prev_evolution,type1,type2
0,1,001,Bulbasaur,http://www.serebii.net/pokemongo/pokemon/001.png,"[Grass, Poison]",0.71 m,6.9 kg,Bulbasaur Candy,25.0,2 km,0.690,69.0,20:00,[1.58],"[Fire, Ice, Flying, Psychic]","[{'num': '002', 'name': 'Ivysaur'}, {'num': '0...",NaN,Grass,Poison
1,2,002,Ivysaur,http://www.serebii.net/pokemongo/pokemon/002.png,"[Grass, Poison]",0.99 m,13.0 kg,Bulbasaur Candy,100.0,Not in Eggs,0.042,4.2,07:00,"[1.2, 1.6]","[Fire, Ice, Flying, Psychic]","[{'num': '003', 'name': 'Venusaur'}]","[{'num': '001', 'name': 'Bulbasaur'}]",Grass,Poison
2,3,003,Venusaur,http://www.serebii.net/pokemongo/pokemon/003.png,"[Grass, Poison]",2.01 m,100.0 kg,Bulbasaur Candy,NaN,Not in Eggs,0.017,1.7,11:30,None,"[Fire, Ice, Flying, Psychic]",NaN,"[{'num': '001', 'name': 'Bulbasaur'}, {'num': ...",Grass,Poison
3,4,004,Charmander,http://www.serebii.net/pokemongo/pokemon/004.png,[Fire],0.61 m,8.5 kg,Charmander Candy,25.0,2 km,0.253,25.3,08:45,[1.65],"[Water, Ground, Rock]","[{'num': '005', 'name': 'Charmeleon'}, {'num':...",NaN,Fire,None
4,5,005,Charmeleon,http://www.serebii.net/pokemongo/pokemon/005.png,[Fire],1.09 m,19.0 kg,Charmander Candy,100.0,Not in Eggs,0.012,1.2,19:00,[1.79],"[Water, Ground, Rock]","[{'num': '006', 'name': 'Charizard'}]","[{'num': '004', 'name': 'Charmander'}]",Fire,None

In [11]:
typegroup = pokedata.groupby("type1").count()["id"]

typegroup

type1
Bug         12
Dragon       3
Electric     9
Fighting     7
Fire        12
Ghost        3
Grass       12
Ground       8
Ice          2
Normal      24
Poison      14
Psychic      8
Rock         9
Water       28
Name: id, dtype: int64

In [12]:

pokecolors_map = {
'Normal': '#A8A77A',
'Fire': '#EE8130',
'Water': '#6390F0',
'Electric': '#F7D02C',
'Grass': '#7AC74C',
'Ice': '#96D9D6',
'Fighting': '#C22E28',
'Poison': '#A33EA1',
'Ground': '#E2BF65',
'Flying': '#A98FF3',
'Psychic': '#F95587',
'Bug': '#A6B91A',
'Rock':'#B6A136',
'Ghost': '#735797',
'Dragon': '#6F35FC',
'Dark': '#705746',
'Steel': '#B7B7CE',
'Fairy': '#D685AD',
}

In [13]:
pokecolors= typegroup.index.map(pokecolors_map)
pokecolors=list(pokecolors)
pokecolors

['#A6B91A',
 '#6F35FC',
 '#F7D02C',
 '#C22E28',
 '#EE8130',
 '#735797',
 '#7AC74C',
 '#E2BF65',
 '#96D9D6',
 '#A8A77A',
 '#A33EA1',
 '#F95587',
 '#B6A136',
 '#6390F0']

In [14]:
fig1 = go.Figure(data=[go.Bar(x=typegroup.index, y=typegroup.values)])

fig1.show()

In [15]:
fig1 = go.Figure(data=[go.Bar(x=typegroup.index, y=typegroup.values, 
                              marker_color = pokecolors)])

fig1.show()

In [16]:
fig2 = go.Figure(
    data=[
    go.Pie(
                        labels= typegroup.index, 
                         values= typegroup.values, 
                         marker=  dict(colors = pokecolors), 
                         title = "Gen 1 Pokemon by Type" 
)])
fig2.show()

In [17]:
pokedata.tail()

,id,num,name,img,type,height,weight,candy,candy_count,egg,spawn_chance,avg_spawns,spawn_time,multipliers,weaknesses,next_evolution,prev_evolution,type1,type2
146,147,147,Dratini,http://www.serebii.net/pokemongo/pokemon/147.png,[Dragon],1.80 m,3.3 kg,Dratini Candy,25.0,10 km,0.3000,30.00,06:41,"[1.83, 1.84]","[Ice, Dragon, Fairy]","[{'num': '148', 'name': 'Dragonair'}, {'num': ...",NaN,Dragon,None
147,148,148,Dragonair,http://www.serebii.net/pokemongo/pokemon/148.png,[Dragon],3.99 m,16.5 kg,Dratini Candy,100.0,Not in Eggs,0.0200,2.00,11:57,[2.05],"[Ice, Dragon, Fairy]","[{'num': '149', 'name': 'Dragonite'}]","[{'num': '147', 'name': 'Dratini'}]",Dragon,None
148,149,149,Dragonite,http://www.serebii.net/pokemongo/pokemon/149.png,"[Dragon, Flying]",2.21 m,210.0 kg,Dratini Candy,NaN,Not in Eggs,0.0011,0.11,23:38,None,"[Ice, Rock, Dragon, Fairy]",NaN,"[{'num': '147', 'name': 'Dratini'}, {'num': '1...",Dragon,Flying
149,150,150,Mewtwo,http://www.serebii.net/pokemongo/pokemon/150.png,[Psychic],2.01 m,122.0 kg,None,NaN,Not in Eggs,0.0000,0.00,N/A,None,"[Bug, Ghost, Dark]",NaN,NaN,Psychic,None
150,151,151,Mew,http://www.serebii.net/pokemongo/pokemon/151.png,[Psychic],0.41 m,4.0 kg,None,NaN,Not in Eggs,0.0000,0.00,N/A,None,"[Bug, Ghost, Dark]",NaN,NaN,Psychic,None

In [18]:
type (pokedata["next_evolution"][150])

float

In [19]:

conditions = [
(pokedata["next_evolution"].apply(isinstance, args=(list,))) & (pokedata["prev_evolution"].apply(isinstance, args=(float,))), 
(pokedata["next_evolution"].apply(isinstance, args=(float,))) & (pokedata["prev_evolution"].apply(isinstance, args=(list,))), 
(pokedata["next_evolution"].apply(isinstance, args=(float,))) & (pokedata["prev_evolution"].apply(isinstance, args=(float,)))

]

choices = ["Starter", "Final", "Lone"]

pokedata["evolution_stage"] = np.select(conditions, choices, default = "Middle")
pokedata.tail()

,id,num,name,img,type,height,weight,candy,candy_count,egg,spawn_chance,avg_spawns,spawn_time,multipliers,weaknesses,next_evolution,prev_evolution,type1,type2,evolution_stage
146,147,147,Dratini,http://www.serebii.net/pokemongo/pokemon/147.png,[Dragon],1.80 m,3.3 kg,Dratini Candy,25.0,10 km,0.3000,30.00,06:41,"[1.83, 1.84]","[Ice, Dragon, Fairy]","[{'num': '148', 'name': 'Dragonair'}, {'num': ...",NaN,Dragon,None,Starter
147,148,148,Dragonair,http://www.serebii.net/pokemongo/pokemon/148.png,[Dragon],3.99 m,16.5 kg,Dratini Candy,100.0,Not in Eggs,0.0200,2.00,11:57,[2.05],"[Ice, Dragon, Fairy]","[{'num': '149', 'name': 'Dragonite'}]","[{'num': '147', 'name': 'Dratini'}]",Dragon,None,Middle
148,149,149,Dragonite,http://www.serebii.net/pokemongo/pokemon/149.png,"[Dragon, Flying]",2.21 m,210.0 kg,Dratini Candy,NaN,Not in Eggs,0.0011,0.11,23:38,None,"[Ice, Rock, Dragon, Fairy]",NaN,"[{'num': '147', 'name': 'Dratini'}, {'num': '1...",Dragon,Flying,Final
149,150,150,Mewtwo,http://www.serebii.net/pokemongo/pokemon/150.png,[Psychic],2.01 m,122.0 kg,None,NaN,Not in Eggs,0.0000,0.00,N/A,None,"[Bug, Ghost, Dark]",NaN,NaN,Psychic,None,Lone
150,151,151,Mew,http://www.serebii.net/pokemongo/pokemon/151.png,[Psychic],0.41 m,4.0 kg,None,NaN,Not in Eggs,0.0000,0.00,N/A,None,"[Bug, Ghost, Dark]",NaN,NaN,Psychic,None,Lone

In [20]:
evolgroup = pokedata.groupby("evolution_stage").count()["id"]
evolgroup

evolution_stage
Final      56
Lone       25
Middle     16
Starter    54
Name: id, dtype: int64

In [21]:
fig3 = make_subplots(rows = 1, cols =2, specs =[[{"type": "domain"}, {"type": "domain"}]])

fig3.add_trace(
    go.Pie(
                        labels= typegroup.index, 
                         values= typegroup.values, 
                         marker=  dict(colors = pokecolors), 
                         title = "Gen 1 Pokemon by Type" 
), 1,1)

fig3.add_trace(
    go.Pie (
    labels=evolgroup.index, 
    values=evolgroup.values, 
    title="Gen 1 pokmon by Evolutionary stage"

), 1,2)

fig3.show()

In [22]:
pokedata.head(1)

,id,num,name,img,type,height,weight,candy,candy_count,egg,spawn_chance,avg_spawns,spawn_time,multipliers,weaknesses,next_evolution,prev_evolution,type1,type2,evolution_stage
0,1,001,Bulbasaur,http://www.serebii.net/pokemongo/pokemon/001.png,"[Grass, Poison]",0.71 m,6.9 kg,Bulbasaur Candy,25.0,2 km,0.69,69.0,20:00,[1.58],"[Fire, Ice, Flying, Psychic]","[{'num': '002', 'name': 'Ivysaur'}, {'num': '0...",NaN,Grass,Poison,Starter

In [23]:
type(pokedata["weight"][0])

str

In [24]:
type(pokedata["weight"][0])

str

In [25]:
pokedata["weight_kg"]=pokedata["weight"].str.replace(" kg", "", regex=False)
pokedata["weight_kg"] = pd.to_numeric(pokedata["weight_kg"])

In [26]:
pokedata["height_m"]=pokedata["height"].str.replace(" m", "", regex=False)
pokedata["height_m"] = pd.to_numeric(pokedata["height_m"])

pokedata.head()

,id,num,name,img,type,height,weight,candy,candy_count,egg,...,spawn_time,multipliers,weaknesses,next_evolution,prev_evolution,type1,type2,evolution_stage,weight_kg,height_m
0,1,001,Bulbasaur,http://www.serebii.net/pokemongo/pokemon/001.png,"[Grass, Poison]",0.71 m,6.9 kg,Bulbasaur Candy,25.0,2 km,...,20:00,[1.58],"[Fire, Ice, Flying, Psychic]","[{'num': '002', 'name': 'Ivysaur'}, {'num': '0...",NaN,Grass,Poison,Starter,6.9,0.71
1,2,002,Ivysaur,http://www.serebii.net/pokemongo/pokemon/002.png,"[Grass, Poison]",0.99 m,13.0 kg,Bulbasaur Candy,100.0,Not in Eggs,...,07:00,"[1.2, 1.6]","[Fire, Ice, Flying, Psychic]","[{'num': '003', 'name': 'Venusaur'}]","[{'num': '001', 'name': 'Bulbasaur'}]",Grass,Poison,Middle,13.0,0.99
2,3,003,Venusaur,http://www.serebii.net/pokemongo/pokemon/003.png,"[Grass, Poison]",2.01 m,100.0 kg,Bulbasaur Candy,NaN,Not in Eggs,...,11:30,None,"[Fire, Ice, Flying, Psychic]",NaN,"[{'num': '001', 'name': 'Bulbasaur'}, {'num': ...",Grass,Poison,Final,100.0,2.01
3,4,004,Charmander,http://www.serebii.net/pokemongo/pokemon/004.png,[Fire],0.61 m,8.5 kg,Charmander Candy,25.0,2 km,...,08:45,[1.65],"[Water, Ground, Rock]","[{'num': '005', 'name': 'Charmeleon'}, {'num':...",NaN,Fire,None,Starter,8.5,0.61
4,5,005,Charmeleon,http://www.serebii.net/pokemongo/pokemon/005.png,[Fire],1.09 m,19.0 kg,Charmander Candy,100.0,Not in Eggs,...,19:00,[1.79],"[Water, Ground, Rock]","[{'num': '006', 'name': 'Charizard'}]","[{'num': '004', 'name': 'Charmander'}]",Fire,None,Middle,19.0,1.09

In [27]:

traces = go.Scatter(
    x=pokedata["height_m"],
    y=pokedata["weight_kg"],
    mode="markers"
)

layout = go.Layout(title=dict(text="Pokemon weight and height"), 
                   xaxis=dict(title="Weight in kg"), 
                   yaxis=dict(title= "Hieght in m"), 
                   
                   )

fig4 = go.Figure(data=[traces], layout=layout)

fig4.show()

In [28]:
trace1 = go.Scatter(
    x=pokedata[pokedata["evolution_stage"] == "Lone"]["height_m"], 
    y=pokedata[pokedata["evolution_stage"] == "Lone"]["weight_kg"],
    customdata=pokedata[pokedata["evolution_stage"] == "Lone"]["name"],
    name="Lone"
)
trace2 = go.Scatter(
    x=pokedata[pokedata["evolution_stage"] == "Starter"]["height_m"], 
    y=pokedata[pokedata["evolution_stage"] == "Starter"]["weight_kg"],
    customdata=pokedata[pokedata["evolution_stage"] == "Starter"]["name"], 
    name="Starter"
)
trace3 = go.Scatter(
    x=pokedata[pokedata["evolution_stage"] == "Middle"]["height_m"], 
    y=pokedata[pokedata["evolution_stage"] == "Middle"]["weight_kg"],
    customdata=pokedata[pokedata["evolution_stage"] == "Middle"]["name"], 
    name="Middle"
)

trace4 = go.Scatter(
    x=pokedata[pokedata["evolution_stage"] == "Final"]["height_m"], 
    y=pokedata[pokedata["evolution_stage"] == "Final"]["weight_kg"],
    customdata=pokedata[pokedata["evolution_stage"] == "Final"]["name"], 
    name="Final"

)

fig4 = go.Figure(data=[trace1, trace2, trace3, trace4], layout=layout)

fig4.update_traces(mode="markers")


layout = go.Layout(title=dict(text="Pokemon weight and height"), 
                   xaxis=dict(title="Weight in kg"), 
                   yaxis=dict(title= "Hieght in m"), 
                   
                   )

fig4 = go.Figure(data=[trace1, trace2, trace3, trace4], layout =layout)

fig4.update_traces(mode = "markers")

fig4.show()

In [29]:
trace1 = go.Scatter(
    x=pokedata[pokedata["evolution_stage"] == "Lone"]["height_m"], 
    y=pokedata[pokedata["evolution_stage"] == "Lone"]["weight_kg"],
    customdata=pokedata[pokedata["evolution_stage"] == "Lone"]["name"],
    text=pokedata[pokedata["evolution_stage"] == "Lone"]["type"],
    marker_color = "lightslategray", 
    name="Lone"
    
    
)
trace2 = go.Scatter(
    x=pokedata[pokedata["evolution_stage"] == "Starter"]["height_m"], 
    y=pokedata[pokedata["evolution_stage"] == "Starter"]["weight_kg"],
    customdata=pokedata[pokedata["evolution_stage"] == "Starter"]["name"], 
    text=pokedata[pokedata["evolution_stage"] == "Lone"]["type"],
    marker_color = "lightslategray", 
    name="Starter"
    
)
trace3 = go.Scatter(
    x=pokedata[pokedata["evolution_stage"] == "Middle"]["height_m"], 
    y=pokedata[pokedata["evolution_stage"] == "Middle"]["weight_kg"],
    customdata=pokedata[pokedata["evolution_stage"] == "Middle"]["name"], 
    text=pokedata[pokedata["evolution_stage"] == "Middle"]["type"],
    marker_color = "mediumvioletred", 
    name="Middle"
    
)

trace4 = go.Scatter(
    x=pokedata[pokedata["evolution_stage"] == "Final"]["height_m"], 
    y=pokedata[pokedata["evolution_stage"] == "Final"]["weight_kg"],
    customdata=pokedata[pokedata["evolution_stage"] == "Final"]["name"], 
    text=pokedata[pokedata["evolution_stage"] == "Final"]["type"],
    marker_color = "indigo", 
    name="Final"
    

)

fig4 = go.Figure(data=[trace1, trace2, trace3, trace4], layout=layout)

fig4.update_traces(mode="markers")


layout = go.Layout(title=dict(text="Pokemon weight and height"), 
                   xaxis=dict(title="Weight in kg"), 
                   yaxis=dict(title= "Hieght in m"), 
                   showlegend=False
                   )

fig4 = go.Figure(data=[trace1, trace2, trace3, trace4], layout =layout)

fig4.update_traces(mode = "markers",
    hovertemplate="<b>%{customdata}<b><br>%{text} Type<b>Weight: %{y}kg<b>Height: %{x}m"
    )


fig4.update_layout(updatemenus = [dict(type = "buttons", direction = "down", xanchor = "left", y = 1.15, yanchor = "top", showactive =True,  
 buttons = list([dict(label = "ALL", method = "update", args = [{"visble": [True, True, True, True]}]), 
   dict(label = "Starter", method = "update", args = [{"visble": [False, True, False, False]}]), 
   dict(label = "Middle", method = "update", args = [{"visble": [False, False, True, False]}]), 
   dict(label = "False", method = "update", args = [{"visble": [False, False, False, True]}]), 
   dict(label = "Lone", method = "update", args = [{"visble": [True, False, False, False]}])
 ]))])


fig4.show()

In [30]:
pokedata.head()

,id,num,name,img,type,height,weight,candy,candy_count,egg,...,spawn_time,multipliers,weaknesses,next_evolution,prev_evolution,type1,type2,evolution_stage,weight_kg,height_m
0,1,001,Bulbasaur,http://www.serebii.net/pokemongo/pokemon/001.png,"[Grass, Poison]",0.71 m,6.9 kg,Bulbasaur Candy,25.0,2 km,...,20:00,[1.58],"[Fire, Ice, Flying, Psychic]","[{'num': '002', 'name': 'Ivysaur'}, {'num': '0...",NaN,Grass,Poison,Starter,6.9,0.71
1,2,002,Ivysaur,http://www.serebii.net/pokemongo/pokemon/002.png,"[Grass, Poison]",0.99 m,13.0 kg,Bulbasaur Candy,100.0,Not in Eggs,...,07:00,"[1.2, 1.6]","[Fire, Ice, Flying, Psychic]","[{'num': '003', 'name': 'Venusaur'}]","[{'num': '001', 'name': 'Bulbasaur'}]",Grass,Poison,Middle,13.0,0.99
2,3,003,Venusaur,http://www.serebii.net/pokemongo/pokemon/003.png,"[Grass, Poison]",2.01 m,100.0 kg,Bulbasaur Candy,NaN,Not in Eggs,...,11:30,None,"[Fire, Ice, Flying, Psychic]",NaN,"[{'num': '001', 'name': 'Bulbasaur'}, {'num': ...",Grass,Poison,Final,100.0,2.01
3,4,004,Charmander,http://www.serebii.net/pokemongo/pokemon/004.png,[Fire],0.61 m,8.5 kg,Charmander Candy,25.0,2 km,...,08:45,[1.65],"[Water, Ground, Rock]","[{'num': '005', 'name': 'Charmeleon'}, {'num':...",NaN,Fire,None,Starter,8.5,0.61
4,5,005,Charmeleon,http://www.serebii.net/pokemongo/pokemon/005.png,[Fire],1.09 m,19.0 kg,Charmander Candy,100.0,Not in Eggs,...,19:00,[1.79],"[Water, Ground, Rock]","[{'num': '006', 'name': 'Charizard'}]","[{'num': '004', 'name': 'Charmander'}]",Fire,None,Middle,19.0,1.09

In [31]:
condtion = pokedata["type1"].notna()& pokedata["type2"].notna()

pokedata["Types"] = np.where(condtion, pokedata["type1"] + " & " + pokedata["type2"], pokedata["type1"])

pokedata.head()

,id,num,name,img,type,height,weight,candy,candy_count,egg,...,multipliers,weaknesses,next_evolution,prev_evolution,type1,type2,evolution_stage,weight_kg,height_m,Types
0,1,001,Bulbasaur,http://www.serebii.net/pokemongo/pokemon/001.png,"[Grass, Poison]",0.71 m,6.9 kg,Bulbasaur Candy,25.0,2 km,...,[1.58],"[Fire, Ice, Flying, Psychic]","[{'num': '002', 'name': 'Ivysaur'}, {'num': '0...",NaN,Grass,Poison,Starter,6.9,0.71,Grass & Poison
1,2,002,Ivysaur,http://www.serebii.net/pokemongo/pokemon/002.png,"[Grass, Poison]",0.99 m,13.0 kg,Bulbasaur Candy,100.0,Not in Eggs,...,"[1.2, 1.6]","[Fire, Ice, Flying, Psychic]","[{'num': '003', 'name': 'Venusaur'}]","[{'num': '001', 'name': 'Bulbasaur'}]",Grass,Poison,Middle,13.0,0.99,Grass & Poison
2,3,003,Venusaur,http://www.serebii.net/pokemongo/pokemon/003.png,"[Grass, Poison]",2.01 m,100.0 kg,Bulbasaur Candy,NaN,Not in Eggs,...,None,"[Fire, Ice, Flying, Psychic]",NaN,"[{'num': '001', 'name': 'Bulbasaur'}, {'num': ...",Grass,Poison,Final,100.0,2.01,Grass & Poison
3,4,004,Charmander,http://www.serebii.net/pokemongo/pokemon/004.png,[Fire],0.61 m,8.5 kg,Charmander Candy,25.0,2 km,...,[1.65],"[Water, Ground, Rock]","[{'num': '005', 'name': 'Charmeleon'}, {'num':...",NaN,Fire,None,Starter,8.5,0.61,Fire
4,5,005,Charmeleon,http://www.serebii.net/pokemongo/pokemon/005.png,[Fire],1.09 m,19.0 kg,Charmander Candy,100.0,Not in Eggs,...,[1.79],"[Water, Ground, Rock]","[{'num': '006', 'name': 'Charizard'}]","[{'num': '004', 'name': 'Charmander'}]",Fire,None,Middle,19.0,1.09,Fire

In [32]:
fig4.to_dict()

{'data': [{'customdata': array(["Farfetch'd", 'Onix', 'Hitmonlee', 'Hitmonchan', 'Lickitung',
          'Chansey', 'Tangela', 'Kangaskhan', 'Mr. Mime', 'Scyther', 'Jynx',
          'Electabuzz', 'Magmar', 'Pinsir', 'Tauros', 'Lapras', 'Ditto',
          'Porygon', 'Aerodactyl', 'Snorlax', 'Articuno', 'Zapdos',
          'Moltres', 'Mewtwo', 'Mew'], dtype=object),
   'marker': {'color': 'lightslategray'},
   'name': 'Lone',
   'text': array([list(['Normal', 'Flying']), list(['Rock', 'Ground']),
          list(['Fighting']), list(['Fighting']), list(['Normal']),
          list(['Normal']), list(['Grass']), list(['Normal']),
          list(['Psychic']), list(['Bug', 'Flying']),
          list(['Ice', 'Psychic']), list(['Electric']), list(['Fire']),
          list(['Bug']), list(['Normal']), list(['Water', 'Ice']),
          list(['Normal']), list(['Normal']), list(['Rock', 'Flying']),
          list(['Normal']), list(['Ice', 'Flying']),
          list(['Electric', 'Flying']), list(['Fire', 'Flying']),
          list(['Psychic']), list(['Psychic'])], dtype=object),
   'x': {'dtype': 'f8',
    'bdata': 'SOF6FK5H6T8UrkfhepQhQAAAAAAAAPg/ZmZmZmZm9j8K16NwPQrzP3E9CtejcPE/rkfhehSu7z+uR+F6FK4BQM3MzMzMzPQ/AAAAAAAA+D9mZmZmZmb2P3E9CtejcPE/zczMzMzM9D8AAAAAAAD4P2ZmZmZmZvY/7FG4HoXrA0AzMzMzMzPTP0jhehSuR+k/zczMzMzM/D/hehSuR+EAQDMzMzMzM/s/mpmZmZmZ+T8UrkfhehQAQBSuR+F6FABAPQrXo3A92j8='},
   'y': {'dtype': 'f8',
    'bdata': 'AAAAAAAALkAAAAAAAEBqQGZmZmZm5khAmpmZmZkZSUAAAAAAAGBQQM3MzMzMTEFAAAAAAACAQUAAAAAAAABUQAAAAAAAQEtAAAAAAAAATEDNzMzMzExEQAAAAAAAAD5AAAAAAABARkAAAAAAAIBLQJqZmZmZGVZAAAAAAACAa0AAAAAAAAAQQAAAAAAAQEJAAAAAAACATUAAAAAAAMB8QDMzMzMzs0tAzczMzMxMSkAAAAAAAABOQAAAAAAAgF5AAAAAAAAAEEA='},
   'type': 'scatter',
   'hovertemplate': '<b>%{customdata}<b><br>%{text} Type<b>Weight: %{y}kg<b>Height: %{x}m',
   'mode': 'markers'},
  {'customdata': array(['Bulbasaur', 'Charmander', 'Squirtle', 'Caterpie', 'Weedle',
          'Pidgey', 'Rattata', 'Spearow', 'Ekans', 'Pikachu', 'Sandshrew',
          'Nidoran ♀ (Female)', 'Nidoran ♂ (Male)', 'Clefairy', 'Vulpix',
          'Jigglypuff', 'Zubat', 'Oddish', 'Paras', 'Venonat', 'Diglett',
          'Meowth', 'Psyduck', 'Mankey', 'Growlithe', 'Poliwag', 'Abra',
          'Machop', 'Bellsprout', 'Tentacool', 'Geodude', 'Ponyta',
          'Slowpoke', 'Magnemite', 'Doduo', 'Seel', 'Grimer', 'Shellder',
          'Gastly', 'Drowzee', 'Krabby', 'Voltorb', 'Exeggcute', 'Cubone',
          'Koffing', 'Rhyhorn', 'Horsea', 'Goldeen', 'Staryu', 'Magikarp',
          'Eevee', 'Omanyte', 'Kabuto', 'Dratini'], dtype=object),
   'marker': {'color': 'lightslategray'},
   'name': 'Starter',
   'text': array([list(['Normal', 'Flying']), list(['Rock', 'Ground']),
          list(['Fighting']), list(['Fighting']), list(['Normal']),
          list(['Normal']), list(['Grass']), list(['Normal']),
          list(['Psychic']), list(['Bug', 'Flying']),
          list(['Ice', 'Psychic']), list(['Electric']), list(['Fire']),
          list(['Bug']), list(['Normal']), list(['Water', 'Ice']),
          list(['Normal']), list(['Normal']), list(['Rock', 'Flying']),
          list(['Normal']), list(['Ice', 'Flying']),
          list(['Electric', 'Flying']), list(['Fire', 'Flying']),
          list(['Psychic']), list(['Psychic'])], dtype=object),
   'x': {'dtype': 'f8',
    'bdata': 'uB6F61G45j+F61G4HoXjP1K4HoXrUeA/MzMzMzMz0z8zMzMzMzPTPzMzMzMzM9M/MzMzMzMz0z8zMzMzMzPTPxSuR+F6FABAPQrXo3A92j+F61G4HoXjPz0K16NwPdo/UrgehetR4D+F61G4HoXjP4XrUbgeheM/UrgehetR4D9I4XoUrkfpP1K4HoXrUeA/MzMzMzMz0z+uR+F6FK7vP5qZmZmZmck/PQrXo3A92j9I4XoUrkfpP1K4HoXrUeA/uB6F61G45j+F61G4HoXjP3sUrkfheuw/SOF6FK5H6T+4HoXrUbjmP3sUrkfheuw/PQrXo3A92j+uR+F6FK7vPwrXo3A9CvM/MzMzMzMz0z9mZmZmZmb2P3E9CtejcPE/exSuR+F67D8zMzMzMzPTP83MzMzMzPQ/rkfhehSu7z89CtejcD3aP1K4HoXrUeA/PQrXo3A92j89CtejcD3aP4XrUbgeheM/rkfhehSu7z89CtejcD3aP4XrUbgeheM/SOF6FK5H6T97FK5H4XrsPzMzMzMzM9M/PQrXo3A92j9SuB6F61HgP83MzMzMzPw/'},
   'y': {'dtype': 'f8',
    'bdata': 'mpmZmZmZG0AAAAAAAAAhQAAAAAAAACJAMzMzMzMzB0CamZmZmZkJQM3MzMzMzPw/AAAAAAAADEAAAAAAAAAAQJqZmZmZmRtAAAAAAAAAGEAAAAAAAAAoQAAAAAAAABxAAAAAAAAAIkAAAAAAAAAeQM3MzMzMzCNAAAAAAAAAFkAAAAAAAAAeQJqZmZmZmRVAmpmZmZmZFUAAAAAAAAA+QJqZmZmZmek/zczMzMzMEECamZmZmZkzQAAAAAAAADxAAAAAAAAAM0DNzMzMzMwoQAAAAAAAgDNAAAAAAACAM0AAAAAAAAAQQAAAAAAAwEZAAAAAAAAANEAAAAAAAAA+QAAAAAAAAEJAAAAAAAAAGECamZmZmZlDQAAAAAAAgFZAAAAAAAAAPkAAAAAAAAAQQJqZmZmZmbk/MzMzMzMzQEAAAAAAAAAaQM3MzMzMzCRAAAAAAAAABEAAAAAAAAAaQAAAAAAAAPA/AAAAAADAXEAAAAAAAAAgQAAAAAAAAC5AAAAAAABAQUAAAAAAAAAkQAAAAAAAABpAAAAAAAAAHkAAAAAAAAAnQGZmZmZmZgpA'},
   'type': 'scatter',
   'hovertemplate': '<b>%{customdata}<b><br>%{text} Type<b>Weight: %{y}kg<b>Height: %{x}m',
   'mode': 'markers'},
  {'customdata': array(['Ivysaur', 'Charmeleon', 'Wartortle', 'Metapod', 'Kakuna',
          'Pidgeotto', 'Nidorina', 'Nidorino', 'Gloom', 'Poliwhirl',
          'Kadabra', 'Machoke', 'Weepinbell', 'Graveler', 'Haunter',
          'Dragonair'], dtype=object),
   'marker': {'color': 'mediumvioletred'},
   'name': 'Middle',
   'text': array([list(['Grass', 'Poison']), list(['Fire']), list(['Water']),
          list(['Bug']), list(['Bug', 'Poison']), list(['Normal', 'Flying']),
          list(['Poison']), list(['Poison']), list(['Grass', 'Poison']),
          list(['Water']), list(['Psychic']), list(['Fighting']),
          list(['Grass', 'Poison']), list(['Rock', 'Ground']),
          list(['Ghost', 'Poison']), list(['Dragon'])], dtype=object),
   'x': {'dtype': 'f8',
    'bdata': 'rkfhehSu7z9xPQrXo3DxP65H4XoUru8/uB6F61G45j+F61G4HoXjP3E9CtejcPE/SOF6FK5H6T97FK5H4XrsP0jhehSuR+k/rkfhehSu7z/NzMzMzMz0PwAAAAAAAPg/rkfhehSu7z+uR+F6FK7vP5qZmZmZmfk/7FG4HoXrD0A='},
   'y': {'dtype': 'f8',
    'bdata': 'AAAAAAAAKkAAAAAAAAAzQAAAAAAAgDZAzczMzMzMI0AAAAAAAAAkQAAAAAAAAD5AAAAAAAAANEAAAAAAAIAzQDMzMzMzMyFAAAAAAAAANEAAAAAAAEBMQAAAAAAAoFFAmpmZmZmZGUAAAAAAAEBaQJqZmZmZmbk/AAAAAACAMEA='},
   'type': 'scatter',
   'hovertemplate': '<b>%{customdata}<b><br>%{text} Type<b>Weight: %{y}kg<b>Height: %{x}m',
   'mode': 'markers'},
  {'customdata': array(['Venusaur', 'Charizard', 'Blastoise', 'Butterfree', 'Beedrill',
          'Pidgeot', 'Raticate', 'Fearow', 'Arbok', 'Raichu', 'Sandslash',
          'Nidoqueen', 'Nidoking', 'Clefable', 'Ninetales', 'Wigglytuff',
          'Golbat', 'Vileplume', 'Parasect', 'Venomoth', 'Dugtrio',
          'Persian', 'Golduck', 'Primeape', 'Arcanine', 'Poliwrath',
          'Alakazam', 'Machamp', 'Victreebel', 'Tentacruel', 'Golem',
          'Rapidash', 'Slowbro', 'Magneton', 'Dodrio', 'Dewgong', 'Muk',
          'Cloyster', 'Gengar', 'Hypno', 'Kingler', 'Electrode', 'Exeggutor',
          'Marowak', 'Weezing', 'Rhydon', 'Seadra', 'Seaking', 'Starmie',
          'Gyarados', 'Vaporeon', 'Jolteon', 'Flareon', 'Omastar',
          'Kabutops', 'Dragonite'], dtype=object),
   'marker': {'color': 'indigo'},
   'name': 'Final',
   'text': array([list(['Grass', 'Poison']), list(['Fire', 'Flying']),
          list(['Water']), list(['Bug', 'Flying']), list(['Bug', 'Poison']),
          list(['Normal', 'Flying']), list(['Normal']),
          list(['Normal', 'Flying']), list(['Poison']), list(['Electric']),
          list(['Ground']), list(['Poison', 'Ground']),
          list(['Poison', 'Ground']), list(['Normal']), list(['Fire']),
          list(['Normal']), list(['Poison', 'Flying']),
          list(['Grass', 'Poison']), list(['Bug', 'Grass']),
          list(['Bug', 'Poison']), list(['Ground']), list(['Normal']),
          list(['Water']), list(['Fighting']), list(['Fire']),
          list(['Water', 'Fighting']), list(['Psychic']), list(['Fighting']),
          list(['Grass', 'Poison']), list(['Water', 'Poison']),
          list(['Rock', 'Ground']), list(['Fire']),
          list(['Water', 'Psychic']), list(['Electric']),
          list(['Normal', 'Flying']), list(['Water', 'Ice']),
          list(['Poison']), list(['Water', 'Ice']),
          list(['Ghost', 'Poison']), list(['Psychic']), list(['Water']),
          list(['Electric']), list(['Grass', 'Psychic']), list(['Ground']),
          list(['Poison']), list(['Ground', 'Rock']), list(['Water']),
          list(['Water']), list(['Water', 'Psychic']),
          list(['Water', 'Flying']), list(['Water']), list(['Electric']),
          list(['Fire']), list(['Rock', 'Water']), list(['Rock', 'Water']),
          list(['Dragon', 'Flying'])], dtype=object),
   'x': {'dtype': 'f8',
    'bdata': 'FK5H4XoUAEAzMzMzMzP7P5qZmZmZmfk/cT0K16Nw8T+uR+F6FK7vPwAAAAAAAPg/uB6F61G45j8K16NwPQrzPxSuR+F6FAxASOF6FK5H6T+uR+F6FK7vP83MzMzMzPQ/ZmZmZmZm9j/NzMzMzMz0P3E9CtejcPE/rkfhehSu7z+amZmZmZn5PwrXo3A9CvM/rkfhehSu7z8AAAAAAAD4P7gehetRuOY/rkfhehSu7z8zMzMzMzP7P65H4XoUru8/j8L1KFyP/j/NzMzMzMz0PwAAAAAAAPg/mpmZmZmZ+T8zMzMzMzP7P5qZmZmZmfk/ZmZmZmZm9j8zMzMzMzP7P5qZmZmZmfk/rkfhehSu7z/NzMzMzMz8PzMzMzMzM/s/CtejcD0K8z8AAAAAAAD4PwAAAAAAAPg/mpmZmZmZ+T/NzMzMzMz0PwrXo3A9CvM/FK5H4XoUAECuR+F6FK7vPwrXo3A9CvM/j8L1KFyP/j8K16NwPQrzP83MzMzMzPQ/cT0K16Nw8T8AAAAAAAAaQK5H4XoUru8/SOF6FK5H6T97FK5H4XrsP65H4XoUru8/zczMzMzM9D+uR+F6FK4BQA=='},
   'y': {'dtype': 'f8',
    'bdata': 'AAAAAAAAWUAAAAAAAKBWQAAAAAAAYFVAAAAAAAAAQEAAAAAAAIA9QAAAAAAAwENAAAAAAACAMkAAAAAAAABDQAAAAAAAQFBAAAAAAAAAPkAAAAAAAIA9QAAAAAAAAE5AAAAAAAAAT0AAAAAAAABEQGZmZmZm5jNAAAAAAAAAKEAAAAAAAIBLQJqZmZmZmTJAAAAAAACAPUAAAAAAAAApQGZmZmZmpkBAAAAAAAAAQEBmZmZmZiZTQAAAAAAAAEBAAAAAAABgY0AAAAAAAABLQAAAAAAAAEhAAAAAAABAYEAAAAAAAAAvQAAAAAAAgEtAAAAAAADAckAAAAAAAMBXQAAAAAAAoFNAAAAAAAAATkDNzMzMzExVQAAAAAAAAF5AAAAAAAAAPkAAAAAAAJBgQAAAAAAAQERAZmZmZmbmUkAAAAAAAABOQGZmZmZmplBAAAAAAAAAXkAAAAAAAIBGQAAAAAAAACNAAAAAAAAAXkAAAAAAAAA5QAAAAAAAgENAAAAAAAAAVEAAAAAAAGBtQAAAAAAAAD1AAAAAAACAOEAAAAAAAAA5QAAAAAAAgEFAAAAAAABAREAAAAAAAEBqQA=='},
   'type': 'scatter',
   'hovertemplate': '<b>%{customdata}<b><br>%{text} Type<b>Weight: %{y}kg<b>Height: %{x}m',
   'mode': 'markers'}],
 'layout': {'showlegend': False,
  'title': {'text': 'Pokemon weight and height'},
  'xaxis': {'title': {'text': 'Weight in kg'}},
  'yaxis': {'title': {'text': 'Hieght in m'}},
  'template': {'data': {'histogram2dcontour': [{'type': 'histogram2dcontour',
      'colorbar': {'outlinewidth': 0, 'ticks': ''},
      'colorscale': [[0.0, '#0d0887'],
       [0.1111111111111111, '#46039f'],
       [0.2222222222222222, '#7201a8'],
       [0.3333333333333333, '#9c179e'],
       [0.4444444444444444, '#bd3786'],
       [0.5555555555555556, '#d8576b'],
       [0.6666666666666666, '#ed7953'],
       [0.7777777777777778, '#fb9f3a'],
       [0.8888888888888888, '#fdca26'],
       [1.0, '#f0f921']]}],
    'choropleth': [{'type': 'choropleth',
      'colorbar': {'outlinewidth': 0, 'ticks': ''}}],
    'histogram2d': [{'type': 'histogram2d',
      'colorbar': {'outlinewidth': 0, 'ticks': ''},
      'colorscale': [[0.0, '#0d0887'],
       [0.1111111111111111, '#46039f'],
       [0.2222222222222222, '#7201a8'],
       [0.3333333333333333, '#9c179e'],
       [0.4444444444444444, '#bd3786'],
       [0.5555555555555556, '#d8576b'],
       [0.6666666666666666, '#ed7953'],
       [0.7777777777777778, '#fb9f3a'],
       [0.8888888888888888, '#fdca26'],
       [1.0, '#f0f921']]}],
    'heatmap': [{'type': 'heatmap',
      'colorbar': {'outlinewidth': 0, 'ticks': ''},
      'colorscale': [[0.0, '#0d0887'],
       [0.1111111111111111, '#46039f'],
       [0.2222222222222222, '#7201a8'],
       [0.3333333333333333, '#9c179e'],
       [0.4444444444444444, '#bd3786'],
       [0.5555555555555556, '#d8576b'],
       [0.6666666666666666, '#ed7953'],
       [0.7777777777777778, '#fb9f3a'],
       [0.8888888888888888, '#fdca26'],
       [1.0, '#f0f921']]}],
    'contourcarpet': [{'type': 'contourcarpet',
      'colorbar': {'outlinewidth': 0, 'ticks': ''}}],
    'contour': [{'type': 'contour',
      'colorbar': {'outlinewidth': 0, 'ticks': ''},
      'colorscale': [[0.0, '#0d0887'],
       [0.1111111111111111, '#46039f'],
       [0.2222222222222222, '#7201a8'],
       [0.3333333333333333, '#9c179e'],
       [0.4444444444444444, '#bd3786'],
       [0.5555555555555556, '#d8576b'],
       [0.6666666666666666, '#ed7953'],
       [0.7777777777777778, '#fb9f3a'],
       [0.8888888888888888, '#fdca26'],
       [1.0, '#f0f921']]}],
    'surface': [{'type': 'surface',
      'colorbar': {'outlinewidth': 0, 'ticks': ''},
      'colorscale': [[0.0, '#0d0887'],
       [0.1111111111111111, '#46039f'],
       [0.2222222222222222, '#7201a8'],
       [0.3333333333333333, '#9c179e'],
       [0.4444444444444444, '#bd3786'],
       [0.5555555555555556, '#d8576b'],
       [0.6666666666666666, '#ed7953'],
       [0.7777777777777778, '#fb9f3a'],
       [0.8888888888888888, '#fdca26'],
       [1.0, '#f0f921']]}],
    'mesh3d': [{'type': 'mesh3d',
      'colorbar': {'outlinewidth': 0, 'ticks': ''}}],
    'scatter': [{'fillpattern': {'fillmode': 'overlay',
       'size': 10,
       'solidity': 0.2},
      'type': 'scatter'}],
    'parcoords': [{'type': 'parcoords',
      'line': {'colorbar': {'outlinewidth': 0, 'ticks': ''}}}],
    'scatterpolargl': [{'type': 'scatterpolargl',
      'marker': {'colorbar': {'outlinewidth': 0, 'ticks': ''}}}],
    'bar': [{'error_x': {'color': '#2a3f5f'},
      'error_y': {'color': '#2a3f5f'},
      'marker': {'line': {'color': '#E5ECF6', 'width': 0.5},
       'pattern': {'fillmode': 'overlay', 'size': 10, 'solidity': 0.2}},
      'type': 'bar'}],
    'scattergeo': [{'type': 'scattergeo',
      'marker': {'colorbar': {'outlinewidth': 0, 'ticks': ''}}}],
    'scatterpolar': [{'type': 'scatterpolar',
      'marker': {'colorbar': {'outlinewidth': 0, 'ticks': ''}}}],
    'histogram': [{'marker': {'pattern': {'fillmode': 'overlay',
        'size': 10,
        'solidity': 0.2}},
      'type': 'histogram'}],
    'scattergl': [{'type': 'scattergl',
      'marker': {'colorbar': {'outlinewidth': 0, 'ticks': ''}}}],
    'scatter3d': [{'type': 'scatter3d',
      'line': {'colorbar': {'outlinewidth': 0, 'ticks': ''}},
      'marker': {'colorbar': {'outlinewidth': 0, 'ticks': ''}}}],
    'scattermap': [{'type': 'scattermap',
      'marker': {'colorbar': {'outlinewidth': 0, 'ticks': ''}}}],
    'scattermapbox': [{'type': 'scattermapbox',
      'marker': {'colorbar': {'outlinewidth': 0, 'ticks': ''}}}],
    'scatterternary': [{'type': 'scatterternary',
      'marker': {'colorbar': {'outlinewidth': 0, 'ticks': ''}}}],
    'scattercarpet': [{'type': 'scattercarpet',
      'marker': {'colorbar': {'outlinewidth': 0, 'ticks': ''}}}],
    'carpet': [{'aaxis': {'endlinecolor': '#2a3f5f',
       'gridcolor': 'white',
       'linecolor': 'white',
       'minorgridcolor': 'white',
       'startlinecolor': '#2a3f5f'},
      'baxis': {'endlinecolor': '#2a3f5f',
       'gridcolor': 'white',
       'linecolor': 'white',
       'minorgridcolor': 'white',
       'startlinecolor': '#2a3f5f'},
      'type': 'carpet'}],
    'table': [{'cells': {'fill': {'color': '#EBF0F8'},
       'line': {'color': 'white'}},
      'header': {'fill': {'color': '#C8D4E3'}, 'line': {'color': 'white'}},
      'type': 'table'}],
    'barpolar': [{'marker': {'line': {'color': '#E5ECF6', 'width': 0.5},
       'pattern': {'fillmode': 'overlay', 'size': 10, 'solidity': 0.2}},
      'type': 'barpolar'}],
    'pie': [{'automargin': True, 'type': 'pie'}]},
   'layout': {'autotypenumbers': 'strict',
    'colorway': ['#636efa',
     '#EF553B',
     '#00cc96',
     '#ab63fa',
     '#FFA15A',
     '#19d3f3',
     '#FF6692',
     '#B6E880',
     '#FF97FF',
     '#FECB52'],
    'font': {'color': '#2a3f5f'},
    'hovermode': 'closest',
    'hoverlabel': {'align': 'left'},
    'paper_bgcolor': 'white',
    'plot_bgcolor': '#E5ECF6',
    'polar': {'bgcolor': '#E5ECF6',
     'angularaxis': {'gridcolor': 'white', 'linecolor': 'white', 'ticks': ''},
     'radialaxis': {'gridcolor': 'white', 'linecolor': 'white', 'ticks': ''}},
    'ternary': {'bgcolor': '#E5ECF6',
     'aaxis': {'gridcolor': 'white', 'linecolor': 'white', 'ticks': ''},
     'baxis': {'gridcolor': 'white', 'linecolor': 'white', 'ticks': ''},
     'caxis': {'gridcolor': 'white', 'linecolor': 'white', 'ticks': ''}},
    'coloraxis': {'colorbar': {'outlinewidth': 0, 'ticks': ''}},
    'colorscale': {'sequential': [[0.0, '#0d0887'],
      [0.1111111111111111, '#46039f'],
      [0.2222222222222222, '#7201a8'],
      [0.3333333333333333, '#9c179e'],
      [0.4444444444444444, '#bd3786'],
      [0.5555555555555556, '#d8576b'],
      [0.6666666666666666, '#ed7953'],
      [0.7777777777777778, '#fb9f3a'],
      [0.8888888888888888, '#fdca26'],
      [1.0, '#f0f921']],
     'sequentialminus': [[0.0, '#0d0887'],
      [0.1111111111111111, '#46039f'],
      [0.2222222222222222, '#7201a8'],
      [0.3333333333333333, '#9c179e'],
      [0.4444444444444444, '#bd3786'],
      [0.5555555555555556, '#d8576b'],
      [0.6666666666666666, '#ed7953'],
      [0.7777777777777778, '#fb9f3a'],
      [0.8888888888888888, '#fdca26'],
      [1.0, '#f0f921']],
     'diverging': [[0, '#8e0152'],
      [0.1, '#c51b7d'],
      [0.2, '#de77ae'],
      [0.3, '#f1b6da'],
      [0.4, '#fde0ef'],
      [0.5, '#f7f7f7'],
      [0.6, '#e6f5d0'],
      [0.7, '#b8e186'],
      [0.8, '#7fbc41'],
      [0.9, '#4d9221'],
      [1, '#276419']]},
    'xaxis': {'gridcolor': 'white',
     'linecolor': 'white',
     'ticks': '',
     'title': {'standoff': 15},
     'zerolinecolor': 'white',
     'automargin': True,
     'zerolinewidth': 2},
    'yaxis': {'gridcolor': 'white',
     'linecolor': 'white',
     'ticks': '',
     'title': {'standoff': 15},
     'zerolinecolor': 'white',
     'automargin': True,
     'zerolinewidth': 2},
    'scene': {'xaxis': {'backgroundcolor': '#E5ECF6',
      'gridcolor': 'white',
      'linecolor': 'white',
      'showbackground': True,
      'ticks': '',
      'zerolinecolor': 'white',
      'gridwidth': 2},
     'yaxis': {'backgroundcolor': '#E5ECF6',
      'gridcolor': 'white',
      'linecolor': 'white',
      'showbackground': True,
      'ticks': '',
      'zerolinecolor': 'white',
      'gridwidth': 2},
     'zaxis': {'backgroundcolor': '#E5ECF6',
      'gridcolor': 'white',
      'linecolor': 'white',
      'showbackground': True,
      'ticks': '',
      'zerolinecolor': 'white',
      'gridwidth': 2}},
    'shapedefaults': {'line': {'color': '#2a3f5f'}},
    'annotationdefaults': {'arrowcolor': '#2a3f5f',
     'arrowhead': 0,
     'arrowwidth': 1},
    'geo': {'bgcolor': 'white',
     'landcolor': '#E5ECF6',
     'subunitcolor': 'white',
     'showland': True,
     'showlakes': True,
     'lakecolor': 'white'},
    'title': {'x': 0.05},
    'mapbox': {'style': 'light'}}},
  'updatemenus': [{'buttons': [{'args': [{'visble': [True, True, True, True]}],
      'label': 'ALL',
      'method': 'update'},
     {'args': [{'visble': [False, True, False, False]}],
      'label': 'Starter',
      'method': 'update'},
     {'args': [{'visble': [False, False, True, False]}],
      'label': 'Middle',
      'method': 'update'},
     {'args': [{'visble': [False, False, False, True]}],
      'label': 'False',
      'method': 'update'},
     {'args': [{'visble': [True, False, False, False]}],
      'label': 'Lone',
      'method': 'update'}],
    'direction': 'down',
    'showactive': True,
    'type': 'buttons',
    'xanchor': 'left',
    'y': 1.15,
    'yanchor': 'top'}]}}