I have decided to revise my initial milestones with a focus on data cleaning and the identification of key columns that yield the most valuable insights for addressing the relevant research questions.

Upon completion of the data cleaning process, I will determine which columns are essential to retain and which may be discarded in order to effectively analyze the trends influencing the voting behavior of Generation Z, specifically targeting individuals aged 18 to 29. Who in my generation chose not to vote, and which pollutions made that decision for them by not participating? 

This approach is intended to support political poster creators in their efforts to engage this demographic meaningfully.

Revised Mildstones: 

1. Clean the data by removing redundant or unnamed columns that do not contain pertinent data. Rename columns that hold the most importance. 

2. Conduct an analysis to identify the individuals or groups who made decisions on behalf of those who chose not to participate in the 2024 election. Visualize trends in political alignment with those who chose to not partipate in the 2024 election. 

3. Visualize trends in political alignment among diverse populations. Highlight and illustrate any increase in support for the Republican candidate among historically underrepresented or diverse demographic groups using clear and accessible visualizations.

In [40]:
import pandas as pd 
import plotly.express as px 
import plotly.io as pio
from matplotlib import pyplot as plt
import seaborn as sns 

# Imports pandas, plotyl.express, plotly.io, metplotlib as pyplot and seaborn. 

# notes: make substaional notes in the markdown cell, Rewrite first Project Milestone, make detailed comments, make data tidy by renamming the coumns, 

# using genZ 18-29 years olds.

In [41]:
vote2024 = pd.read_csv("vote01_2024.csv")

# This code cell loads vote01_2024.csv

In [42]:
vote2024.head(10)

# Head is used to shows the first 10 rows.

,Table with row headers in columns A and B and column headers in rows 4 through 6,Unnamed: 1,Unnamed: 2,Unnamed: 3,Unnamed: 4,Unnamed: 5,Unnamed: 6,Unnamed: 7,Unnamed: 8,Unnamed: 9,Unnamed: 10,Unnamed: 11,Unnamed: 12,Unnamed: 13,Unnamed: 14,Unnamed: 15,Unnamed: 16,Unnamed: 17
0,"Table 1. Reported Voting and Registration, by ...",NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,(Numbers in thousands),NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,Characteristics,NaN,Total population,United States citizen,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Total population,NaN
3,NaN,NaN,NaN,Total citizen population,Reported registered,NaN,Reported not registered,NaN,No response to registration1,NaN,Reported voted,NaN,Reported not voted,NaN,No response to voting2,NaN,Reported registered,Reported voted
4,NaN,NaN,NaN,NaN,Number,Percent,Number,Percent,Number,Percent,Number,Percent,Number,Percent,Number,Percent,Percent,Percent
5,BOTH SEXES,Total 18 years and over,"260,363","236,138","173,854",73.6,"28,009",11.9,"34,275",14.5,"154,308",65.3,"48,480",20.5,"33,351",14.1,66.8,59.3
6,BOTH SEXES,18 to 24 years,"29,986","27,548","16,052",58.3,"5,955",21.6,"5,542",20.1,"13,150",47.7,"9,033",32.8,"5,366",19.5,53.5,43.9
7,BOTH SEXES,25 to 34 years,"44,385","38,963","26,637",68.4,"6,156",15.8,"6,170",15.8,"22,148",56.8,"10,928",28.0,"5,887",15.1,60.0,49.9
8,BOTH SEXES,35 to 44 years,"44,380","38,229","27,920",73.0,"4,859",12.7,"5,450",14.3,"24,340",63.7,"8,555",22.4,"5,334",14.0,62.9,54.8
9,BOTH SEXES,45 to 54 years,"40,089","35,422","27,091",76.5,"3,457",9.8,"4,874",13.8,"24,339",68.7,"6,271",17.7,"4,812",13.6,67.6,60.7

In [43]:
vote2024 = pd.read_csv("vote01_2024.csv", skiprows=6)

# Called vote2024.csv, skipped rows 1-6 unkowns, removes Nan, unamed catergories used to tidy the data. chaged to remove more unknow data tites.

In [44]:
vote2024.head(10)

# Head is used to shows the first 10 rows.

,BOTH SEXES,Total 18 years and over,"260,363","236,138","173,854",73.6,"28,009",11.9,"34,275",14.5,"154,308",65.3,"48,480",20.5,"33,351",14.1,66.8,59.3
0,BOTH SEXES,18 to 24 years,"29,986","27,548","16,052",58.3,"5,955",21.6,"5,542",20.1,"13,150",47.7,"9,033",32.8,"5,366",19.5,53.5,43.9
1,BOTH SEXES,25 to 34 years,"44,385","38,963","26,637",68.4,"6,156",15.8,"6,170",15.8,"22,148",56.8,"10,928",28.0,"5,887",15.1,60.0,49.9
2,BOTH SEXES,35 to 44 years,"44,380","38,229","27,920",73.0,"4,859",12.7,"5,450",14.3,"24,340",63.7,"8,555",22.4,"5,334",14.0,62.9,54.8
3,BOTH SEXES,45 to 54 years,"40,089","35,422","27,091",76.5,"3,457",9.8,"4,874",13.8,"24,339",68.7,"6,271",17.7,"4,812",13.6,67.6,60.7
4,BOTH SEXES,55 to 64 years,"41,115","37,982","29,584",77.9,"3,400",9.0,"4,997",13.2,"27,015",71.1,"6,016",15.8,"4,951",13.0,72.0,65.7
5,BOTH SEXES,65 to 74 years,"35,236","33,753","27,161",80.5,"2,504",7.4,"4,088",12.1,"25,389",75.2,"4,352",12.9,"4,011",11.9,77.1,72.1
6,BOTH SEXES,75 years and over,"25,172","24,242","19,410",80.1,"1,677",6.9,"3,155",13.0,"17,928",74.0,"3,325",13.7,"2,989",12.3,77.1,71.2
7,BOTH SEXES,18 years,"4,474","4,258","1,872",44.0,"1,191",28.0,"1,196",28.1,"1,586",37.3,"1,505",35.3,"1,167",27.4,41.8,35.5
8,BOTH SEXES,19 years,"4,062","3,796","2,233",58.8,924,24.3,639,16.8,"1,744",45.9,"1,452",38.2,601,15.8,55.0,42.9
9,BOTH SEXES,20 years,"4,100","3,733","2,116",56.7,883,23.7,733,19.6,"1,664",44.6,"1,370",36.7,699,18.7,51.6,40.6

In [45]:
vote2024.columns

# Used to see the columns, 

#The columns need proper labeling to accurately reflect the Census Data.

Index(['BOTH SEXES', 'Total 18 years and over', '260,363', '236,138',
       '173,854', '73.6', '28,009', '11.9', '34,275', '14.5', '154,308',
       '65.3', '48,480', '20.5', '33,351', '14.1', '66.8', '59.3'],
      dtype='object')

In [46]:
vote2024_fixed = vote2024.copy()

In [47]:
vote2024_fixed = vote2024_fixed.rename(columns={
    "pid3_c": "party_identification",  # makes pid3_C = Party indetification
    "sex_c": "gender",                 # makes sex = gender 
    "ideo5": "ideology",               # makes Ideology 
    "age": "age"                       # make age 
})

# Cleans the code using pid3_C which kaes the data set and rename the columns for better understanding.

In [ ]:
vote2024_fixed = vote2024_fixed.rename(columns={
    "age": "age",
    "pid3_c": "party_identification",
    "ideo5": "ideology_5pt",
    "sex_c": "gender",
    "race": "race_ethnicity",
    "educ": "education_level",
    "income": "household_income",
    "vote2024": "voted_2024",
    "register": "registered_to_vote"
})

# renamed columns will contuie cleaning data, and double check if this code is correct and it reanmes the needed columns